"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import { Baby, CirclePlus, MapPin, Menu, MessageCircle, Navigation, ScanFace, Smile, Stethoscope, X, type LucideIcon } from "lucide-react";
import { useState } from "react";

const whatsapp = "https://wa.me/5521993770229?text=Ol%C3%A1%2C%20LB%20Odontologia!%20Gostaria%20de%20agendar%20uma%20avalia%C3%A7%C3%A3o.";
const instagram = "https://www.instagram.com/lb.odontologia_/";
const address = "Edifício Center Offices - R. da Conceição, 125 - Sala 608 - Centro, Niterói - RJ, 24020-080";
const directions = "https://www.google.com/maps/dir/?api=1&destination=Edif%C3%ADcio%20Center%20Offices%2C%20Rua%20da%20Concei%C3%A7%C3%A3o%2C%20125%2C%20Sala%20608%2C%20Niter%C3%B3i%2C%20RJ";
const map = "https://www.google.com/maps?q=Edif%C3%ADcio%20Center%20Offices%2C%20Rua%20da%20Concei%C3%A7%C3%A3o%2C%20125%2C%20Sala%20608%2C%20Niter%C3%B3i%2C%20RJ&z=17&output=embed";

const team = [
  { name: "Dra. Larissa", specialty: "Equipe LB Odontologia", photo: "/team-larissa.png" },
  { name: "Dra. Beatriz", specialty: "Equipe LB Odontologia", photo: "/team-beatriz.png" },
  { name: "Dr. Fábio", specialty: "Equipe LB Odontologia", photo: "/team-fabio.png" },
  { name: "Dr. Vinícius", specialty: "Equipe LB Odontologia", photo: "/team-vinicius.png" },
  { name: "Dra. Larissa Santana", specialty: "Equipe LB Odontologia", photo: "/team-larissa-santana.png" },
  { name: "Dr. Paulo", specialty: "Equipe LB Odontologia", photo: "/team-paulo.png" },
];
const treatments: [string, string, string, LucideIcon][] = [
  ["01", "Ortodontia e Invisalign", "Alinhamento discreto e planejado para a sua rotina.", ScanFace],
  ["02", "Odontopediatria", "Cuidado acolhedor para os sorrisos que estão começando.", Baby],
  ["03", "Dentística e estética", "Naturalidade e harmonia em cada detalhe do sorriso.", Smile],
  ["04", "Endodontia e implantes", "Tecnologia e precisão para saúde e função oral.", CirclePlus],
  ["05", "Clínica geral", "Prevenção e acompanhamento para toda a família.", Stethoscope],
];

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <motion.div className={className} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.6, delay }}>{children}</motion.div>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <main className="overflow-x-hidden bg-[#f7f3ea] text-[#342217]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-[#8a4a1e]/15 bg-[#faf6ee]/90 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 md:px-8"><a href="#inicio" className="flex items-center gap-3" aria-label="LB Odontologia"><span className="relative h-11 w-11 overflow-hidden rounded-full border border-[#d9a441]/50 bg-[#fbf5e9]"><Image src="/logo-lb.png" alt="Monograma LB da LB Odontologia" fill className="object-contain p-1" sizes="44px" /></span><span className="leading-tight"><b className="block text-[15px]">LB Odontologia</b><span className="text-xs text-[#735340]">Especializada</span></span></a><nav className="hidden items-center gap-7 text-sm font-medium text-[#664330] lg:flex"><a href="#inicio">Início</a><a href="#equipe">Equipe</a><a href="#tratamentos">Tratamentos</a><a href="#localizacao">Localização</a></nav><button className="grid h-10 w-10 place-items-center rounded-full bg-[#f0ddae] text-[#6b3410] lg:hidden" aria-label="Abrir menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div>{menuOpen && <nav className="border-t border-[#8a4a1e]/15 bg-[#faf6ee] px-5 py-5 lg:hidden"><a className="block py-3" href="#inicio" onClick={() => setMenuOpen(false)}>Início</a><a className="block py-3" href="#equipe" onClick={() => setMenuOpen(false)}>Equipe</a><a className="block py-3" href="#tratamentos" onClick={() => setMenuOpen(false)}>Tratamentos</a><a className="block py-3" href="#localizacao" onClick={() => setMenuOpen(false)}>Localização</a></nav>}</header>

    <section id="inicio" className="relative isolate min-h-[770px] overflow-hidden bg-[#f7f3ea] pt-[76px]"><div className="absolute left-1/2 top-24 -z-10 h-[520px] w-[520px] -translate-x-1/2 rounded-full bg-[#e8b84b]/25 blur-3xl" /><div className="mx-auto grid max-w-7xl items-center px-5 pb-16 pt-16 md:px-8 lg:min-h-[720px] lg:grid-cols-[.92fr_1.08fr] lg:pt-6"><Reveal className="relative z-10 max-w-xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#d9a441]/35 bg-white/70 px-3 py-2 text-xs font-bold uppercase tracking-[.12em] text-[#8a4a1e]"><Smile size={14} /> Odontologia para toda a família</div><h1 className="text-[3.35rem] font-black leading-[.96] text-[#402615] sm:text-7xl lg:text-[5.5rem]">Seu sorriso merece <span className="bg-gradient-to-r from-[#e8b84b] via-[#b76d28] to-[#6b3410] bg-clip-text text-transparent">cuidado completo.</span></h1><p className="mt-7 max-w-md text-lg leading-relaxed text-[#765847]">Uma equipe de especialistas para acolher cada fase da sua saúde bucal com tecnologia, leveza e atenção.</p><a href="#localizacao" className="mt-8 inline-flex items-center gap-2 rounded-full border border-[#b98242] bg-white px-6 py-4 font-bold text-[#6b3410] transition hover:bg-[#fff9ed]"><MapPin size={19} /> Ver localização</a></Reveal><Reveal delay={0.15} className="relative mt-2 h-[430px] sm:h-[520px] lg:mt-0 lg:h-[650px]"><p className="pointer-events-none absolute inset-x-0 top-[21%] text-center text-4xl font-black leading-none text-[#8a4a1e]/[.06] sm:text-5xl lg:text-6xl">CUIDADO<br />INTEGRAL</p><motion.div animate={{ y: [0, -10, 0], rotate: [0, 1, 0] }} transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }} className="absolute inset-0"><Image src="/hero-tooth.png" alt="Dente 3D representando tratamentos da LB Odontologia" fill priority className="object-contain" sizes="(max-width: 1024px) 100vw, 55vw" /></motion.div></Reveal></div></section>

    <section id="equipe" className="mx-auto max-w-7xl px-5 py-24 md:px-8 lg:py-32"><Reveal><p className="text-sm font-bold uppercase tracking-[.16em] text-[#9a5e25]">Nossa equipe</p><h2 className="mt-4 text-4xl font-black text-[#402615] sm:text-5xl">Especialistas para cada sorriso.</h2><p className="mt-5 max-w-2xl text-lg leading-relaxed text-[#765847]">Seis profissionais unidos por um atendimento integrado, acolhedor e preciso.</p></Reveal><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{team.map(({ name, specialty, photo }, index) => <Reveal key={name} delay={index * .06} className="overflow-hidden rounded-2xl border border-[#d9a441]/25 bg-[#fffdf8] shadow-sm"><div className="relative aspect-[4/3] overflow-hidden bg-[#f3dfa8]"><Image src={photo} alt={`Retrato profissional de ${name}, da equipe LB Odontologia`} fill className="object-cover object-top" sizes="(max-width: 640px) 100vw, 33vw" /><span className="absolute bottom-3 left-3 rounded-full bg-[#fffaf0]/90 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#6b3410]">Equipe LB</span></div><div className="p-5"><h3 className="font-black text-[#402615]">{name}</h3><p className="mt-2 text-sm leading-relaxed text-[#765847]">{specialty}</p></div></Reveal>)}</div></section>

    <section id="tratamentos" className="bg-[#2e1b12] py-24 text-white lg:py-32"><div className="mx-auto max-w-7xl px-5 md:px-8"><Reveal className="grid gap-8 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#e8b84b]">Tratamentos</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">Cuidado em todas as fases.</h2></div><p className="border-l-2 border-[#d9a441] pl-5 text-lg leading-relaxed text-[#eadbce]">Do primeiro sorriso à reabilitação oral, nossa equipe une especialidades em um plano de cuidado completo.</p></Reveal><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{treatments.map(([number, title, text, Icon], index) => <Reveal key={title} delay={index * .05} className="relative min-h-[15rem] overflow-hidden rounded-2xl border border-white/15 bg-white/[.06] p-7 transition hover:-translate-y-1 hover:bg-white/[.11]"><div className="flex items-start justify-between"><span className="text-sm font-black tracking-[.16em] text-[#e8b84b]">{number}</span><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#e8b84b]/15 text-[#e8b84b]"><Icon size={21} /></span></div><h3 className="mt-10 text-2xl font-black">{title}</h3><p className="mt-3 leading-relaxed text-[#eadbce]">{text}</p><div className="absolute bottom-0 left-0 h-1 w-full bg-[#d9a441]" /></Reveal>)}</div></div></section>

    <section id="localizacao" className="mx-auto grid max-w-7xl gap-10 px-5 py-24 md:px-8 lg:grid-cols-[.9fr_1.1fr] lg:py-32"><Reveal><p className="text-sm font-bold uppercase tracking-[.16em] text-[#9a5e25]">Localização</p><h2 className="mt-4 text-4xl font-black text-[#402615] sm:text-5xl">Perto de você, em Niterói.</h2><p className="mt-5 max-w-md text-lg leading-relaxed text-[#765847]">Um espaço preparado para o cuidado odontológico de toda a família.</p><div className="mt-8 space-y-5"><Contact icon={<MapPin />} title="Clínica" text={address} /><Contact icon={<MessageCircle />} title="WhatsApp" text="(21) 99377-0229" /></div><a href={directions} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full border border-[#b98242] px-5 py-3 text-sm font-bold text-[#6b3410] transition hover:bg-[#fff9ed]"><Navigation size={18} /> Como chegar</a></Reveal><Reveal delay={.1} className="relative h-[400px] overflow-hidden rounded-2xl bg-[#ead9b5]"><iframe title="Mapa da LB Odontologia no Edifício Center Offices, Niterói" className="absolute inset-0 h-[400px] w-full border-0" loading="lazy" src={map} /><div className="pointer-events-none absolute bottom-5 left-5 rounded-xl bg-[#fffaf0]/95 p-4 shadow-lg"><p className="font-bold text-[#402615]">Center Offices</p><p className="mt-1 text-sm text-[#765847]">Sala 608 · Centro, Niterói</p></div></Reveal></section>
    <footer className="bg-[#2e1b12] text-white"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-10 sm:flex-row sm:items-center sm:justify-between md:px-8"><div className="flex items-center gap-3"><span className="relative h-10 w-10 overflow-hidden rounded-full bg-[#f7f3ea]"><Image src="/logo-lb.png" alt="Logotipo LB Odontologia" fill className="object-contain p-1" sizes="40px" /></span><div><p className="font-black">LB Odontologia</p><p className="text-sm text-[#eadbce]">Cuidado especializado</p></div></div><div className="flex flex-wrap items-center gap-4 text-sm"><a href="/politica-de-privacidade" className="font-bold text-[#eadbce] hover:text-[#e8b84b]">Privacidade</a><a href={instagram} target="_blank" rel="noreferrer" className="font-bold text-[#eadbce] hover:text-[#e8b84b]">@lb.odontologia_</a></div></div></footer><a href={whatsapp} target="_blank" rel="noreferrer" aria-label="Falar com a LB Odontologia pelo WhatsApp" className="fixed bottom-5 right-5 z-[60] inline-flex h-14 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-[#e8b84b] to-[#8a4a1e] px-4 text-sm font-bold text-white shadow-xl shadow-[#6b3410]/25 transition hover:scale-105 sm:px-5"><MessageCircle size={22} /><span className="hidden sm:inline">WhatsApp</span></a>
  </main>;
}
function Contact({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="flex items-center gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#f0ddae] text-[#8a4a1e]">{icon}</span><div><p className="font-bold text-[#402615]">{title}</p><p className="mt-0.5 text-sm text-[#765847]">{text}</p></div></div>; }
